name: Release Notes Only

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag name for release notes"
        required: true

permissions:
  contents: write

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Notes
        id: release_notes
        uses: actions/github-script@v6
        with:
          script: |
            const notes = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG_NAME,
            });
            return notes.data.body;
        env:
          TAG_NAME: ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.release_notes.outputs.result }}
          draft: false
          prerelease: false
